name: Run with DD Agent

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'URL to test'
        required: true
        default: 'https://example.com'
      VU:
        description: 'Number of virtual users'
        required: true
        default: '10'
      DURATION:
        description: 'Test duration (e.g., 30s, 1m)'
        required: true
        default: '30s'
      TAG:
        description: 'Tag for the run'
        required: true
        default: 'Regression'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set TimeStamp
        run: echo "TIMESTAMP=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_ENV
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Create Docker Network
        run: docker network create my_network
      - name: Start Datadog Agent
        run: |
          docker run -d --name datadog-agent \
          --network my_network \
          -e DD_API_KEY=${{ secrets.DATADOG_API_KEY }} \
          -e DD_APM_ENABLED=true \
          -e DD_LOGS_ENABLED=true \
          datadog/agent:latest
      - name: Run K6 tests with Datadog Agent
        run: |
          docker run --network my_network -v ${{ github.workspace }}:/test loadimpact/k6 run /test/perf.js --out statsd --out  json=./results/result_$TIMESTAMP.json 
          --env VU=${{github.event.inputs.VU}} \
          --env URL=${{github.event.inputs.URL}} \
          --env DURATION=${{github.event.inputs.DURATION}}
          # Replace 'your_k6_script.js' with the path to your K6 script

      - name: Commit and push results
        run: |
          timestamp=$(date +%Y%m%d%H%M%S)
          echo "K6 test results saved at results_$timestamp.json"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./results/result_$TIMESTAMP.json
          git commit -m "Add K6 results for $timestamp"
          git pull -r
          git push
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
